### ISSUE TITLE
pytest for Python 3.6 uses Python 3.8

### ISSUE THREAD

**Issue by erwanp** [erwanp/pytexit#17]
See https://github.com/erwanp/pytexit/issues/16#issuecomment-752941030_

There may be something wrong in our .travis.yml

**Comment by alxy** [comment]
Yeah, I think you are downloading/installing Miniconda and also creating an environment, but you never actually activate it: https://github.com/erwanp/pytexit/blob/master/.travis.yml#L25-L27

So probably it just uses the default travis Python evnironment?

**Comment by erwanp** [comment]
No reason. I use conda for most of my other projects (ex https://github.com/radis/radis ) which heavily depends on all of the big scientific librairies,  and I initially copied the .travis environment from there. But we could make it much simpler !

**Comment by erwanp** [comment]
re-opening,  866368b fixes #18 not #17 ;)
