### ISSUE TITLE
Linting : black, isort, pre-commit

### ISSUE THREAD

**Issue by erwanp** [erwanp/pytexit#20]
Standardize development tools. Run: 

- [ ] black
- [ ] isort
- [ ] pre-commit

and associated Lint tests

**Comment by manelbdcosta** [comment]
Hey @erwanp! Do you mind if I take this issue? If not, could you clarify at what stage you would prefer to have black and isort be ran? Travis or pre-commit hook? 

Thanks!

**Comment by erwanp** [comment]
Hello @manelbdcosta, please take it ! 

In another (larger) project RADIS, we have a [linting stage set-up directly on Travis-CI](https://github.com/radis/radis/blob/develop/.travis.yml) right after the main tests. I was envisioning something similar. If you have a better idea go for it !

**Comment by manelbdcosta** [comment]
@erwanp sounds good! Will start working on it then 😃 . Could you assign it to me please?

Thanks!

**Comment by manelbdcosta** [comment]
Opened [an issue](https://github.com/pre-commit/pre-commit/issues/1806) to try and figure out an issue I'm having with isort on python2.7 (working for all other python version, [branch](https://github.com/manelbdcosta/pytexit/tree/feature/Issue-20_DevTools))

**Comment by erwanp** [comment]
Nice @manelbdcosta it seems it's time to stop support of Python 2. Just remove it from the tested versions. 
If pytexit keeps working on it perfect, else it's OK at this point.

**Comment by erwanp** [comment]
Closed by #27
