### ISSUE TITLE
\times is conjugated with variable name

### ISSUE THREAD

**Issue by turner-eng** [erwanp/pytexit#31]
![image](https://user-images.githubusercontent.com/62496935/109629028-5fe6f780-7b7e-11eb-96bf-b2acaa47515d.png)

**Comment by emetor** [comment]
This issue is solved in the current version, "\times" is only output where necessary:

`$$q=\operatorname{max}\left(1.5w_k, 1.3q_{EK}+1.5\times0.2 w_k\right)$$`

![issue31](https://user-images.githubusercontent.com/22505717/131840105-3c1ba5d2-19a0-4c48-8e92-9aac9c56643d.png)
