### ISSUE TITLE
There is no way to disable the '$$' enclosure of a py2tex output

### ISSUE THREAD

**Issue by turner-eng** [erwanp/pytexit#33]
![image](https://user-images.githubusercontent.com/62496935/109631962-78a4dc80-7b81-11eb-8fce-54c804752542.png)

**Comment by erwanp** [comment]
Could add an option... or remove it entirely. How / where do you use your own Latex formula afterwards ?

**Comment by turner-eng** [comment]
I am using py2tex almost anywhere in my tex document, so in-text, custom environment and actions like concatenation before output.

**Comment by turner-eng** [comment]
I will have a look at the test_functions.py and make sure it runs okay

**Comment by emetor** [comment]
Done with pull request #43, which was part of pull request #34 by @turner-eng
