### ISSUE TITLE
pow(x,y) doesn't work in py2tex()

### ISSUE THREAD

**Issue by turner-eng** [erwanp/pytexit#35]
py2tex("pow(a,b)") currently produces:
$$\operatorname{pow}\left(a, b\right)$$
instead of:
a^b 

Do you want pow(a,b) to result completely like a**b?

If yes, we should do the following shown in the picture
1. change the name "power" with "pow" in core.py->visit_Call() and
2. in the same function, remove the "self.parenthesis()" around args[0]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/62496935/110429929-98d71d00-80e6-11eb-8377-ab380aad569c.png">

reference
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/62496935/110430579-8b6e6280-80e7-11eb-8bca-7e2c72f74a3b.png">

**Comment by erwanp** [comment]
Yes let's do it ! I've never used `pow` before but it's standard Python syntax

**Comment by emetor** [comment]
pow(x,y) enabled in commit #44
