### ISSUE TITLE
printing parameters

### ISSUE THREAD

**Issue by jon-durand** [erwanp/pytexit#52]
Hi I was playing with this package and was trying to set the printing parameters globally like this:
```
py2tex.print_formula = False
```

But it had no effect within my Jupyter Notebook (specifically Google Colab).
It only worked when done for each function call like this:
```python
py2tex('x = 2*sqrt(2*pi*T_e/m_e)*(DeltaE/(T_e))**2*a_0**2 * k',print_latex=False, print_formula=True)
```

Is it possible to do it once at the start of a notebook and not have to add "print_latex=False, print_formula=True" on each function call?

**Comment by erwanp** [comment]
Hello, we could easily define a global variable ; I'm marking this as "Good First Issue"

**Comment by OfirSiboni** [comment]
Hey,
took care of it - I've created 2 `PRINT_FORMULA` and `PRINT_LATEX` global variables. creating a pull request.

**Comment by jon-durand** [comment]
Sorry for the late reply. But thank you both!
