### ISSUE TITLE
Treatment of pow(x,2) => x^2 (etc.)

### ISSUE THREAD

**Issue by mm002a** [erwanp/pytexit#53]
First, thanks for all the work which has gone into developing this tool. It is a great idea and I am hoping to use it quite a bit.

I have run the test under spyder and there seem to been a few changes which are not reflected in the "Expected results."
These ARE trivial e.g. extra braces "{}" in the tex; a "\left(  \right )" replacing a "( )"- obviously not real problems.

One feature request, please.
Please can we get  "pow(x,2)" to map to "$$x^2$$".
The expression "power(x,2)" transforms into "$$x^2$$". I assume that is line 665 of core.py.
I don't understand the python function power( ).
To my shame, I have never done any serious object oriented programming, so I got lost in the coding of core.py
This would be great.

Sorry, I cannot offer a proper fix, Chris Thompson

**Comment by erwanp** [comment]
Hello @mm002a , actually was already implemented : https://github.com/erwanp/pytexit/blob/master/pytexit/core/core.py#L251 
by @emetor in https://github.com/erwanp/pytexit/pull/44

I'll release a new version soon so you can enjoy it !

**Comment by erwanp** [comment]
Done in https://github.com/erwanp/pytexit/releases/tag/0.4.0 , please confirm it works

**Comment by mm002a** [comment]
Wow, thanks very much indeed.
I'll give you more feedback as I gain experience, if that would be helpful.
I think of Jupyter as an aid to reproducible computing and this is a REAL
step forward.
Chris Thompson

**Comment by erwanp** [comment]
Great it works. You should thank @emetor who implemented it
