### ISSUE TITLE
Unicode character documentation

### ISSUE THREAD

**Issue by WesDH** [erwanp/pytexit#66]
Noticed while working on previous issue that perhaps a table listing supported Unicode characters would be useful to add to the Read the Docs. Maybe with a few additional examples? Example:

<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-ca80334f-7fff-2941-7688-0994c2224ba9">

Supported Unicode Characters
--

</div>
<div dir="ltr" style="margin-left:0pt;" align="left" id="docs-internal-guid-a2fe1bc4-7fff-6da0-8fc0-0c9789060364">

Character | Name | As chr()
-- | -- | --
α | alpha | chr(945)
β | beta | chr(946)

</div>
And so on...
<br><br>
Please let me know if this is OK and I will create the table documentation. It looks as if docs/userguide.rst would need to be edited.

**Comment by WesDH** [comment]
I was unable to build the documentation source on ReadTheDocs to test my changes. As a workaround, I am posting some code I believe can be reconciled into userguide.srt. Feel free to use this documentation if deemed useful. I created two versions of the same table, as there are apparently two ways to create tables and I wasn't sure if one way was preferred over another:

**Comment by erwanp** [comment]
First option looks easier to maintain. Let's push the changes and see how it renders on Readthedocs

**Comment by erwanp** [comment]
Docs passed following #67 , are you ok with the results ?
