### ISSUE TITLE
Publish pytexit on conda-forge

### ISSUE THREAD

**Issue by Krande** [erwanp/pytexit#70]
Hey, 

first of all, thank you for sharing pytexit! I have found pytexit to be a really helpful tool, and I would like to help publish it on conda-forge so that I can depend on it in a package I am about to publish myself on conda-forge ([paradoc](https://github.com/Krande/paradoc)).

Let me know what you think? 

Best Regards
Kristoffer

**Comment by erwanp** [comment]
Glad that it helps. At this point Pytexit is maintained and improved by its users. 

To publish it on Conda you will need to build a conda-recipee. Have you already done that ?

**Comment by Krande** [comment]
Not yet, but that's easy. With your permission, I can submit a conda-forge PR with a recipe for pytexit and tag you in that PR? I can also add you as a maintainer of the feedstock if you want?

**Comment by Krande** [comment]
Hey @erwanp, I took the liberty of making a PR for a pytexit conda-forge recipe -> https://github.com/conda-forge/staged-recipes/pull/27187. 

If you want to be added as a co-maintainer just let me know :)

**Comment by erwanp** [comment]
Amazing. No need to add me! Just let me know if you need anything

**Comment by Krande** [comment]
pytexit is now up on conda-forge: 

feedstock: https://github.com/conda-forge/pytexit-feedstock
package: https://anaconda.org/conda-forge/pytexit

closing this issue
