### ISSUE TITLE
Problem with fractions with negative numerator and for2tex

### ISSUE THREAD

**Issue by troelsfrostholm** [erwanp/pytexit#9]
`In [30]: pytexit.for2tex("-10*1/T")`
`<IPython.core.display.Latex object>`
`$$\frac{1-10}{T}$$`
`Out[30]: u'$$\\frac{1-10}{T}$$'`

**Comment by erwanp** [comment]
Indeed, there was an error in the simplification of `a*2 -> 2a` expressions when `a` was negative
Fixed in bf51b53, I'm pushing a new version in a minute

Thank you!

**Comment by troelsfrostholm** [comment]
Thanks a lot for fixing it
